apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-conn
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  host: "http://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local:15672/"
---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: {{ .Release.Name }}-rabbitmq-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretTargetRef:
  - parameter: host
    name: {{ .Release.Name }}-rabbitmq-conn
    namespace: {{ .Release.Namespace }}
    key: host
---