apiVersion: apps/v1
kind: Deployment
metadata:
  name: buffer-service-router-carbonstat #buffer-service-router- carbonstat 
  namespace: carbonstat
  labels:
    # Recommended labels
    app.kubernetes.io/name:        buffer-service-router
    app.kubernetes.io/instance:    carbonshift
    app.kubernetes.io/component:   router
    app.kubernetes.io/part-of:     carbonshift
    carbonshift/parent-service:    carbonstat
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name:        buffer-service-router
      app.kubernetes.io/instance:    carbonshift
  template:
    metadata:
      labels:
        app.kubernetes.io/name:        buffer-service-router
        app.kubernetes.io/instance:    carbonshift
        app.kubernetes.io/component:   router
        app.kubernetes.io/part-of:     carbonshift
        app.kubernetes.io/managed-by:  carbonshift-operator
        carbonshift/parent-service:    carbonstat
    spec:
      containers:
      - name: buffer-service-router
        image: ghcr.io/belgio99/k8s-carbonshift/buffer-service-router:latest
        imagePullPolicy: Always
        env:
        - name: RABBIT_URL
          value: "amqp://carbonuser:supersecret@carbonshift-rabbitmq.carbonshift-system.svc.cluster.local:5672"
        - name: TRAFFIC_SCHEDULE_NAME
          value: "TrafficSchedule"
        - name: METRICS_PORT
          value: "8001"
        - name: SERVICE_NAME
          value: carbonstat
        - name: SVC_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: buffer-service-router-carbonstat #buffer-service-router- carbonstat 
  namespace: carbonstat
  labels:
    app.kubernetes.io/name:        buffer-service-router
    app.kubernetes.io/instance:    carbonshift
    app.kubernetes.io/component:   router
    app.kubernetes.io/part-of:     carbonshift
    carbonshift/parent-service:    carbonstat
spec:
  selector:
    app.kubernetes.io/name:        buffer-service-router
    app.kubernetes.io/instance:    carbonshift
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 8001
    targetPort: 8001
  type: ClusterIP