# This file contains the default values for the CarbonShift umbrella chart.
# It is used to set default values for the chart and its dependencies.

rabbitmq:
  auth:
    username: carbonuser
    password: supersecret
    erlangCookie: verysecretcookie
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  clustering:
    forceBoot: true
  metrics:
    enabled: true
    

# Istio component configuration
base:
  # Assuming 'base' chart doesn't install namespaced resources directly or respects Release.Namespace
  # No specific namespace override needed here typically, but monitor if errors persist.
  {}

global:
  istioNamespace: carbonshift-system
  hub: docker.io/istio
  tag: 1.25.0
  proxy:
    autoInject: disabled

istiod:
  namespace: carbonshift-system
  sidecarInjectorWebhook:
    enableNamespacesByDefault: false

gateway:
  name: gateway
  namespace: carbonshift-system
# Add other sub-chart overrides below if needed
# Disable sidecar injection for non-gateway pods
decision-engine:
  podAnnotations:
    sidecar.istio.io/inject: "false"
buffer-service:
  podAnnotations:
    sidecar.istio.io/inject: "true"
carbonshift-operator:
  podAnnotations:
    sidecar.istio.io/inject: "false"

kube-prometheus-stack:
  kube-state-metrics:
    metricLabelsAllowlist:
      - deployments=[*]
      - pods=[*]
      - namespaces=[*]
      - services=[*]
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false