# This file contains the default values for the CarbonShift umbrella chart.
# It is used to set default values for the chart and its dependencies.

rabbitmq:
  auth:
    username: carbonuser
    password: supersecret
    erlangCookie: verysecretcookie
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi