---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.carbonshift.io
  resources:
  - trafficschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.carbonshift.io
  resources:
  - trafficschedules/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.carbonshift.io
  resources:
  - trafficschedules/status
  verbs:
  - get
  - patch
  - update
