apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "decision-engine.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: carbonshift
    {{- include "decision-engine.labels" . | nindent 4 }}
spec:
   selector:
      matchLabels:
         app.kubernetes.io/instance: carbonshift
         app.kubernetes.io/name: decision-engine
   endpoints:
      - port: metrics
        interval: 15s
        path: /metrics