apiVersion: scheduling.carbonrouter.io/v1alpha1
kind: TrafficSchedule
metadata:
  name: traffic-schedule
spec:
  target:
    autoscaling:
      minReplicaCount: 0
      maxReplicaCount: 12
      cooldownPeriod: 120
      cpuUtilization: 90
  router:
    debug: true
    autoscaling:
      minReplicaCount: 1
      maxReplicaCount: 15
      cooldownPeriod: 60
      cpuUtilization: 80
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
  consumer:
    debug: true
    autoscaling:
      minReplicaCount: 0
      maxReplicaCount: 12
      cooldownPeriod: 120
      cpuUtilization: 90
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
  scheduler:
    targetError: "0.15"
    creditMin: "-2.0"
    creditMax: "2.0"
    creditWindow: 10
    policy: forecast-aware
    validFor: 300
    discoveryInterval: 30
    carbonTarget: "150"
    carbonTimeout: 5000
    carbonCacheTTL: 300
    throttleMin: "0.01"
    throttleIntensityFloor: "250.0"
    throttleIntensityCeiling: "300.0"