name: Build and Push Docker Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changed-services:
    runs-on: ubuntu-22.04
    outputs:
      changed-services: ${{ env.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed files
        id: detect
        uses: tj-actions/changed-files@v45.0.8
        with:
          files: |
            carbonstat/**
            buffer-service/**
            decision-engine/**

      - name: Parse changed services
        id: parse-changes
        run: |
          services="carbonstat buffer-service decision-engine"
          changed_services=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            changed_services="$services"
          else
            for service in $services; do
              if [[ "${{ steps.detect.outputs.all_changed_files }}" =~ (^|[[:space:]])${service}/.*($|[[:space:]]) ]]; then
                changed_services="$changed_services $service"
              fi
            done
          fi
          echo "Changed services (containers to be rebuilt): $changed_services"
          echo "changed=$changed_services" >> $GITHUB_ENV

  build-containers:
    needs: detect-changed-services
    if: needs.detect-changed-services.outputs.changed-services != ''
    runs-on: ubuntu-latest
    concurrency: 
      group: build-containers-${{ matrix.service }}
      cancel-in-progress: false
    strategy:
      matrix:
        service: [
          carbonstat,
          buffer-service,
          decision-engine
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        if: contains(needs.detect-changed-services.outputs.changed-services, matrix.service)
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/k8s-carbonshift/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository_owner }}/k8s-carbonshift/${{ matrix.service }}:${{ steps.vars.outputs.sha_short }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64