name: Build and Push Docker Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changed-services:
    runs-on: ubuntu-24.04
    outputs:
      changed-services: ${{ steps.parse-changes.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed files
        id: detect
        uses: tj-actions/changed-files@v46
        with:
          files: |
            carbonstat/**
            buffer-service/**
            decision-engine/**
            operator/**

      - name: Parse changed services
        id: parse-changes
        run: |
          services="carbonstat buffer-service decision-engine operator"
          changed_services=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            changed_services="$services"
          else
            for service in $services; do
              if [[ "${{ steps.detect.outputs.all_changed_files }}" =~ (^|[[:space:]])${service}/.*($|[[:space:]]) ]]; then
                changed_services="$changed_services $service"
              fi
            done
          fi
          echo "Changed services (containers to be rebuilt): $changed_services"
          echo "changed=$changed_services" >> $GITHUB_OUTPUT

  build-containers:
    needs: detect-changed-services
    if: needs.detect-changed-services.outputs.changed-services != ''
    runs-on: ubuntu-latest
    concurrency: 
      group: build-containers-${{ matrix.service }}
      cancel-in-progress: false
    strategy:
      matrix:
        service: [
          carbonstat,
          decision-engine,
          operator
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        if: contains(needs.detect-changed-services.outputs.changed-services, matrix.service)
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/k8s-carbonshift/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository_owner }}/k8s-carbonshift/${{ matrix.service }}:${{ steps.vars.outputs.sha_short }}
          push: true
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}
          platforms: linux/amd64,linux/arm64

  build-buffer-service:
    needs: detect-changed-services
    if: contains(needs.detect-changed-services.outputs.changed-services, 'buffer-service')
    runs-on: ubuntu-latest
    concurrency:
      group: build-buffer-service-${{ matrix.variant }}
      cancel-in-progress: false
    strategy:
      matrix:
        variant: [router, consumer]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push buffer-service ${{ matrix.variant }}
        uses: docker/build-push-action@v6
        with:
          context: ./buffer-service
          file: ./buffer-service/Dockerfile.${{ matrix.variant }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/k8s-carbonshift/buffer-service-${{ matrix.variant }}:latest
            ghcr.io/${{ github.repository_owner }}/k8s-carbonshift/buffer-service-${{ matrix.variant }}:${{ steps.vars.outputs.sha_short }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=buffer-service-${{ matrix.variant }}
          cache-to:   type=gha,mode=max,scope=buffer-service-${{ matrix.variant }}
