name: Build and Push Docker Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      changed-services: ${{ env.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed files
        id: detect
        uses: tj-actions/changed-files@v45.0.8
        with:
          files: |
            carbonstat/**

      - name: Parse changed services
        id: parse-changes
        run: |
          services="carbonstat"
          changed_services=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            changed_services="$services"
          else
            for service in $services; do
              if [[ "${{ steps.detect.outputs.all_changed_files }}" =~ (^|[[:space:]])${service}/.*($|[[:space:]]) ]]; then
                changed_services="$changed_services $service"
              fi
            done
          fi
          echo "Changed services: $changed_services"
          echo "changed=$changed_services" >> $GITHUB_ENV

  print-changed-containers:
    needs: detect-changes
    runs-on: ubuntu-22.04
    steps:
      - name: Print changed containers
        run: |
          echo "Containers to be rebuilt: ${{ needs.detect-changes.outputs.changed-services }}"

  build-carbonstat:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed-services, 'carbonstat')
    concurrency:
      group: build-carbonstat
      cancel-in-progress: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: ./carbonstat
          file: ./carbonstat/Dockerfile
          tags: |
            ghcr.io/belgio99/k8s-carbonaware-scheduler/carbonstat:latest
            ghcr.io/belgio99/k8s-carbonaware-scheduler/carbonstat:${{ steps.vars.outputs.sha_short }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64